# Generated by Django 3.2 on 2021-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=50)),
                ('registered_funding', models.TextField()),
                ('nonregistered_funding', models.TextField(null=True)),
                ('active_substance', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('med_name', models.CharField(max_length=100)),
                ('med_form', models.CharField(max_length=40, null=True)),
                ('dose', models.CharField(max_length=40, null=True)),
                ('pack_size', models.CharField(max_length=50)),
                ('limit_group', models.TextField(null=True)),
                ('payment_lvl', models.CharField(choices=[('50%', 'Smaller Prc'), ('30%', 'Bigger Prc'), ('ryczałt', 'Const'), ('bezpłatny do limitu', 'Free')], max_length=20)),
                ('patient_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('official_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('refund_limit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
