# Generated by Django 3.2 on 2021-05-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=50)),
                ('registered_funding', models.TextField()),
                ('nonregistered_funding', models.TextField(null=True)),
                ('active_substance', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('med_name', models.CharField(max_length=100)),
                ('med_form', models.CharField(max_length=40, null=True)),
                ('dose', models.CharField(max_length=40, null=True)),
                ('pack_size', models.CharField(max_length=50)),
                ('limit_group', models.TextField(null=True)),
                ('payment_lvl', models.CharField(choices=[('50%', '50 %'), ('30%', '30 %'), ('ryczałt', 'Ryczałt'), ('bezpłatny do limitu', 'Bezpłatny do limitu')], max_length=20)),
                ('patient_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('official_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('refund_limit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('diff_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medsApp.drug')),
            ],
        ),
    ]
