# Generated by Django 3.2.2 on 2021-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='company_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
