# Generated by Django 3.2 on 2021-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='payment_lvl',
            field=models.CharField(choices=[('50%', '50 %'), ('30%', '30 %'), ('ryczałt', 'Ryczałt'), ('bezpłatny do limitu', 'Bezpłatny do limitu')], max_length=20),
        ),
    ]
